CUDA_VISIBLE_DEVICES=0 python main.py \
    --num_epochs 10 \
    --batch_size 16 \
    --clip_lr 5e-6 \
    --model_lr 1e-4 \
    --linear_lr 1e-2 \
    --save_path "./save" \
    --model_name DAIE \
    --mlp_output 300 \
    --gat_layer 3 \
    --dropout 0.2 \
    --beta 0.01 \
    --theta 0.5 \
    --gamml 0.5 \
    --lam 1 \
    --temperature 0.7 \
    --imgpri True \
    --nsw True
